[package]

name = "glob_prime"
version = "0.0.1"
authors = ["Jorge Israel Peña <jorge.israel.p@gmail.com>"]

[dependencies]
glob = "*"

[dependencies.regex]
path = "../regex"

[dependencies.regex_macros]
path = "../regex/regex_macros"
